name: Build and Push Docker Image

on:
  push:
    branches:
      - 'feature/add-github-actions'
      # - main       # Rama de producción
      # - develop    # Rama de desarrollo
      # - 'release/*' # Opcional: ramas de release según GitFlow
      # - 'feature/*' # Opcional: ramas de feature según GitFlow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure Java and Maven
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Generate JAR
      - name: Build with Maven
        run: mvn clean package

      # 4. Lista el contenido de la carpeta target
      - name: Verify JAR file
        run: ls -l target/


      # 4. Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            bitraw/api-pc-building-sim:latest
            bitraw/api-pc-building-sim:${{ github.ref_name }}
